version: '3.9'
services:
    web:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html
        container_name: flashchord-web
